language: c
os: linux
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install libblas-dev liblapack-dev
        - sudo apt-get install luajit
        - sudo apt-get install libluajit-dev
  
compiler:
        - clang
        - gcc
 
script:
        - cd source
        - mkdir build
        - cd build
        - cmake ..
        - make
        - ./unittest/cg_unittest 
