language: c
os: linux
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install libblas-dev liblapack-dev
        - sudo apt-get install lua5.2
  
compiler:
        - clang
        - gcc
 
script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - cp libcgraph.so ../lua/
        - cd ../lua
        - lua test.lua
