language: c
os: linux
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install libblas-dev liblapack-dev
	- sudo apt-get install lua
  
compiler:
        - clang
        - gcc
 
script:
        - cd build
        - cmake ..
        - make
        - lua test.lua
