language:c
os:
        - linux
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install libblas-dev liblapack-dev
  
compiler:
        - clang
        - gcc
 
script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - ./ccgraph
